[package]
name = "monetdb-arrow"
description = "Conversion between MonetDB's binary result-set / COPY BINARY wire format and Apache Arrow arrays"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arrow-array.workspace = true
arrow-schema.workspace = true
chrono.workspace = true
monetdb.workspace = true
uuid.workspace = true

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
