manifest_version = 1
name = "ADBC Driver for MonetDB"
description = "ADBC driver for MonetDB: Arrow-native reads and writes"
version = "0.8.3"
publisher = "William Laurén"
license = "MIT AND MPL-2.0"
url = "https://github.com/wlaur/adbc-driver-monetdb"

[ADBC]
version = "1.1.0"

[ADBC.features]
supported = [
    "bulk ingestion",
    "cancellation",
    "database metadata",
    "parameterized queries",
    "prepared statements",
    "select queries",
    "SQL",
    "transactions",
    "update queries",
]
unsupported = [
    "cross-catalog ingestion",
    "incremental queries",
    "partitioned data",
    "progress reporting",
    "read-only connections",
    "setting current catalog",
    "statistics",
    "Substrait",
    "transaction isolation levels",
]

[Driver]
entrypoint = "AdbcDriverMonetdbInit"

[Files]
driver = "adbc_driver_monetdb.dll"
