manifest_version = 1
name = "ADBC Driver for MonetDB"
version = "0.1.0"
publisher = "William Laurén"
license = "MIT AND MPL-2.0"

[ADBC]
version = "1.1.0"

[ADBC.features]
supported = [
    "bulk ingestion",
    "cancellation",
    "database metadata",
    "parameterized queries",
    "prepared statements",
    "select queries",
    "SQL",
    "transactions",
    "update queries",
]
unsupported = [
    "incremental queries",
    "partitioned data",
    "statistics",
    "Substrait",
]

[Driver]
entrypoint = "AdbcDriverMonetdbInit"

[Files]
driver = "adbc_driver_monetdb.dll"
